---

- name: Create EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    key_name: eng74-amaan-aws
    region: eu-west-1
    image: ami-0dc8d444ee2a42d8a
    id: "eng74-amaan-TESTING_DEPLOYMENT"
    # security group
    group_id: sg-03e057be852ef2701
    subnet_id: subnet-01d3b243860b05d75
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Installing dependencies
      apt:
        pkg:
          - python3
          - python3-pip
        state: present

    - name: Python dependencies
      pip:
        name:
          - boto
          - boto3
          - nose
          - tornado
          - awscli
        state: present

    - name: Get instance facts
      ec2_instance_facts:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
      register: result

    - name: Create EC2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        assign_public_ip: true
        key_name: "{{ key_name }}"
        id: "{{ id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ group_id }}"
        image: "{{ image }}"
        instance_type: t2.micro
        region: "{{ region }}"
        wait: true
        count: 1
        instance_tags:
          Name: eng74_amaan_Testing_DEPLOYMENT

  tags: ['never', 'create_ec2']
