---

- name: Setting up the development environment
  hosts: all
  vars:
    app_dir: /home/vagrant/it_jobswatch_devops_project
    host_name: deployment_env

  # gathers state of the machine before running
  gather_facts: yes

  # give root persmissions
  become: yes

  tasks:
    - name: Set hostname to "{{ host_name }}"
      hostname:
        name: "{{ host_name }}"


    - name: Sort out the terminal
      shell: bash {{ app_dir }}/provisioning/deployment_machine/terminal.sh

    - name: Upgrade and update
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python3
      apt:
        pkg:
          - python3
          - python3-pip

    - name: Set Python3 as default Python
      shell: |
        update-alternatives --install /usr/bin/python python /usr/bin/python3.6 10
      become: yes

      #     - name: Checkout a github repo and use refspec to fetch all pull requests
      #       git:
      #         repo: https://github.com/AmaanHUB/it_jobswatch_devops_project
      #         dest: /home/ubuntu/it_jobswatch_devops_project

    - name: Install Python packages from a requirements file
      pip:
        requirements: requirements.txt
      args:
        chdir: "{{ app_dir }}"
