---

- name: Setting up the development environment
  hosts: deployment_env
  vars:
    app_dir: /home/ubuntu/it_jobswatch_devops_project
    host_name: deployment_env

  # gathers state of the machine before running
  gather_facts: yes

  # give root persmissions
  become: yes

  tasks:
    - name: Set hostname to "{{ host_name }}"
      hostname:
        name: "{{ host_name }}"

    - name: Upgrade and update
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python3
      apt:
        pkg:
          - python3
          - python3-pip

    - name: Set Python3 as default Python
      shell: |
        update-alternatives --install /usr/bin/python python /usr/bin/python3.6 10
      become: yes


    - name: show the app_dir variable
      debug:
        msg: "{{ app_dir }}"

      # to sort out, no such file or directory error
      #     - name: Install Python requirements from the file provided
      #       pip:
      #         requirements: requirements.txt
      #       args:
      #         chdir: "{{ app_dir }}"

    - name: Sort out python requirements manually
      pip:
        requirements: requirements.txt
      args:
        chdir: "{{ app_dir }}"
      debug:
        msg: In
        shell: "pwd && ls -l"
