---

- name: Setting up the testing environment
  hosts: testing_env

  vars:
    host_name: testing_env

  gather_facts: yes
  become: yes

  tasks:
    - name: Set hostname to "{{ host_name }}"
      hostname:
        name: "{{ host_name }}"

        #     - name: Sort out the terminal (uses same script as deployment)
        #       script: /home/amaan/Assorted-Projects/Work/Sparta-Training/DevOps/it_jobswatch_devops_project/provisioning/deployment_machine/terminal.sh

    - name: Upgrade and update
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600


    - name: Install prerequisites
      apt:
        pkg:
          - python3
          - python3-pip
          - software-properties-common

    - name: Get docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the docker repository to the source list
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      notify: Update

    - name: Install docker
      apt:
        pkg:
          - docker-ce
      notify: Restart docker

    - name: Install docker interpreter
      pip:
        name: docker-py
        state: present

      # sort out this bit
    - name: Pull Jenkins docker container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: present
        exposed_ports:
          - 8000
        published_ports:
          - "8080:8080"

    - name: Install python3 within the Jenkins docker container
      shell: |
        docker exec -u 0 -it jenkins "bash"
        apt-get install python3 python3-pip

  handlers:
    - name: Update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Restart docker
      service:
        name: docker
        state: restarted
